### PR TITLE
Fixes #188, NPE when AwsInjector injects TracingContext without AmznTraceId extra

### LINKED ISSUE #188: NullPointerException occurs on 0.23.2
## Describe the Bug

When we upgrade brave-propagation-aws 0.23.1 to 0.23.2, we encounter NullPointerException occurs on test using `@SpringBootTest` and `TestRestTemplate`.

## Steps to Reproduce

Here is a minimal code to reproduce it:
https://github.com/ueokande/brave-npe

Clone the repository, move into the cloned directory, and you can confirm by the following commands:

```console
# Test with brave-propagation-aws 0.23.1
$ mvn clean test
-> Pass all tests

# Test with brave-propagation-aws 0.23.2
$ sed -i 's/0.23.1/0.23.2/' pom.xml 
$ mvn clean test
-> Fail on HealthControllerTest
```

## Expected Behaviour
Pass all tests

### PR DESCRIPTION
**Pull request by JochemKuijpers**
This bug was introduced in 0.23.2 by #186 and reported in #188.
The introduced tests now pass and should help avoid regression in this area.

### CODE REVIEW

**Comment by JochemKuijpers** [comment]
@jeqo Sorry for the tag; I don't mean to be impatient, but I'd like to get a new artifact with this fix released as soon as reasonably possible. You helped me out with https://github.com/openzipkin/brave/pull/1372. Do you maintain this project, or know who does?

**Review by jeqo — APPROVED** [review]
@JochemKuijpers thanks for the fix! LGTM.

**Comment by jeqo** [comment]
@JochemKuijpers [0.23.5 is released now](https://github.com/openzipkin/zipkin-aws/releases/tag/0.23.5), should be in maven central during the day -- thanks again for the fix!

**Comment by JochemKuijpers** [comment]
Thanks so much 😄

**Pull request merged**
