### PR TITLE
Update to latest zipkin-reporter2

### PR DESCRIPTION
**Pull request by mbischo**
Addresses https://github.com/openzipkin/zipkin-aws/issues/67

### CODE REVIEW

**Comment by adriancole** [comment]
LGTM

**Comment by adriancole** [comment]
We should do a quick scan that any shading that is no longer needed is
removed (possibly there is none)

**Comment by llinder** [comment]
I took a quick pass through the code base and it looks like this covers the only cases where `zipkin2.reporter.internal.BaseCall` as used.  There is a shaded copy to avoid a dependency here https://github.com/openzipkin/zipkin-aws/blob/master/storage-xray-udp/src/main/java/zipkin2/storage/xray_udp/BaseCall.java.   @mbischo could you take a look at removing that and using `zipkin2.Call.Base` instead?  It doesn't seem strictly necessary to do that for this PR but it would be a good time to clean it up if doesn't incur adding a dependency anymore.

**Comment by mbischo** [comment]
Closing this PR and opening a new one. Straddling the new year is throwing off the license-check plugin.

**Pull request closed without merging**
