### PR TITLE
Add tests for XrayUDPStorage / Reporter.

### PR DESCRIPTION
**Pull request by anuraaga**
I was randomly looking at the xray storage and want to convert to using Netty to likely improve performance a lot. But that would require benchmarking and reasoning about whether adding a dependency on Netty is OK (I guess so since other storage like elasticsearch has it).

In the meantime, it shouldn't require reasoning to use Netty for tests, which would help in the event we make a change to the storage implementation.

### CODE REVIEW

**Comment by adriancole** [comment]
main thing is this is used for a reporter which cant assume a netty dep. we
could move the non netty code over there I suppose and split the two?

https://github.com/openzipkin/zipkin-aws/blob/master/reporter-xray-udp/pom.xml#L35

**Comment by anuraaga** [comment]
Yup did notice that and agree with splitting - it's a small amount of code to duplicate but with a good expectation for impact on the storage (non-reporter) side

**Comment by adriancole** [comment]
sgtm

**Comment by anuraaga** [comment]
Added tests for reporter too in anticipation of the split.

**Pull request merged**
